language: generic

before_install:
 - git fetch --depth=1000 --tags origin master
 - alias python=python${TRAVIS_PYTHON_VERSION}
 - sudo add-apt-repository -y ppa:pymor/stable
 - sudo add-apt-repository -y ppa:fenics-packages/fenics
 - sudo apt-get update -qq
 # these are packages not on travis' whitelist/only in our ppa
 - sudo apt-get install -y -qq python-docopt python-pytest python-opengl python-distribute ipython python-pyside python-pyvtk
 - for pkg in ipyparallel pytest-cov python-coveralls ; do sudo -E pip install ${pkg} ; done
 # using aptitude here because it auto-fixes problems
 - sudo aptitude install -y -q dolfin-dev python-dolfin
 - python -c 'import  dolfin' || echo "import dolfin failed"

install:
 - python setup.py build_ext -i

sudo: required
dist: trusty

script:
  # this runs in pytest in a fake, auto numbered, X Server
  - xvfb-run -a py.test -k "${PYTEST_MARKER}"

notifications:
  email: 
    on_success: change
    on_failure: change

after_success:
  - coveralls

branches:
  except:
    - gh-pages

env:
  - PYTEST_MARKER="not slow"
  - PYTEST_MARKER="slow"

addons:
  apt:
    packages:
    - debhelper
    - python-pip
    - python-markupsafe
    - git
    - cython
    - xvfb
    - libopenmpi-dev
    - python-virtualenv
    - python-numpy
    - python-sphinx
    - python-scipy
    - python-matplotlib
    - python-sympy
    - python-dev
    - python3
    - dh-make
    - python-docutils
    - build-essential
    - libblas-dev
    - liblapack-dev
    - libatlas-dev
    - libsuitesparse-dev
    - gfortran
    - libqt4-dev
    - gmsh

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx
